interface Main {
    _id: string;
    name: string;
    bonuses: number;
    kills: number;
    death: number;
    revives: number;
    teamkills: number;
    kd: number;
    exp: number;
    possess: object;
    roles: object;
    squad: object;
    matches: {
        matches: number;
        winrate: number;
        won: number;
        lose: number;
        cmdwon: number;
        cmdlose: number;
        cmdwinrate: number;
    };
    weapons: object;
    date?: number;
    seedRole?: boolean;
}
export declare function connectToDatabase(dbURL: string, database: string): Promise<void>;
export declare function writeLastModUpdateDate(modID: string, date: Date): Promise<void>;
export declare function getModLastUpdateDate(modID: string): Promise<string | undefined>;
export declare function createUserIfNullableOrUpdateName(steamID: string, name: string): Promise<void>;
export declare function updateUserBonuses(steamID: string, count: number, id: number): Promise<void>;
export declare function updateRoles(steamID: string, role: string): Promise<void>;
export declare function updateTimes(steamID: string, field: string, name: string): Promise<void>;
export declare function updatePossess(steamID: string, field: string): Promise<void>;
export declare function getUserDataWithSteamID(steamID: string): Promise<import("mongodb").WithId<Main> | undefined>;
export declare function updateUser(steamID: string, field: string, weapon?: string): Promise<void>;
export declare function updateGames(steamID: string, field: string): Promise<void>;
export declare function serverHistoryLayers(serverID: number, rnsHistoryLayers?: string): Promise<void>;
export declare function getHistoryLayers(serverID: number): Promise<string[]>;
export declare function cleanHistoryLayers(serverID: number): Promise<void>;
export declare function serverHistoryFactions(serverID: number, faction: string): Promise<void>;
export declare function getHistoryFactions(serverID: number): Promise<string[]>;
export declare function cleanHistoryFactions(serverID: number): Promise<void>;
export declare function serverHistoryUnitTypes(serverID: number, unitType: string): Promise<void>;
export declare function getHistoryUnitTypes(serverID: number): Promise<string[]>;
export declare function cleanHistoryUnitTypes(serverID: number): Promise<void>;
export declare function getTimeStampForRestartServer(serverID: number): Promise<number | undefined>;
export declare function createTimeStampForRestartServer(serverID: number): Promise<void>;
export declare function updateCollectionTemp(user: {
    _id: string;
}, doc: object, name: string): Promise<void>;
export declare function creatingTimeStamp(): Promise<void>;
export {};
